[workspace]
authors = ["Daniel Esteban Palma Igor <daniel.palma.i@ug.uchile.cl>"]
channels = ["conda-forge", "bioconda"]
name = "FeGenie"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pyhmmer = ">=0.11.1,<0.12"
requests = ">=2.32.4,<3"
ipython = ">=9.4.0,<10"
